package model.pojo;
// Generated Jun 14, 2021 3:18:10 PM by Hibernate Tools 4.3.1



/**
 * Karyawan generated by hbm2java
 */
public class Karyawan  implements java.io.Serializable {


     private Integer id;
     private String namaKaryawan;
     private String jenisKelamin;
     private String jabatan;
     private String alamat;

    public Karyawan() {
    }

    public Karyawan(String namaKaryawan, String jenisKelamin, String jabatan, String alamat) {
       this.namaKaryawan = namaKaryawan;
       this.jenisKelamin = jenisKelamin;
       this.jabatan = jabatan;
       this.alamat = alamat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaKaryawan() {
        return this.namaKaryawan;
    }
    
    public void setNamaKaryawan(String namaKaryawan) {
        this.namaKaryawan = namaKaryawan;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


