package model.pojo;
// Generated Jun 14, 2021 3:18:10 PM by Hibernate Tools 4.3.1



/**
 * Obat generated by hbm2java
 */
public class Obat  implements java.io.Serializable {


     private Integer id;
     private String namaObat;
     private String jenisObat;
     private String harga;

    public Obat() {
    }

    public Obat(String namaObat, String jenisObat, String harga) {
       this.namaObat = namaObat;
       this.jenisObat = jenisObat;
       this.harga = harga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaObat() {
        return this.namaObat;
    }
    
    public void setNamaObat(String namaObat) {
        this.namaObat = namaObat;
    }
    public String getJenisObat() {
        return this.jenisObat;
    }
    
    public void setJenisObat(String jenisObat) {
        this.jenisObat = jenisObat;
    }
    public String getHarga() {
        return this.harga;
    }
    
    public void setHarga(String harga) {
        this.harga = harga;
    }




}


